### PR TITLE
Added Google Login.

### PR DESCRIPTION
**Pull request by janamkhatiwada**
- Added Login with google in UI.
- Added a DB field to check whether user is allowed or not. IF it is authencated with google allowed is set to true.
- Modified build.sh the sed command had some issues so it wasnot able to update the Dockerfile. Also the arm64 architecutre was missing added it too.
- Gogle configurations can be passed as Environment Variables. Here we can update secrets , cliendID from google developer console and allowed domains checked which email domains are allowed. Required ENV variables for google login to work.
>          GOOGLE_CLIENT_ID
>          GOOGLE_CLIENT_SECRET
>          GOOGLE_REDIRECT_URL
>          ALLOWED_DOMAINS

- Two new modules were added,
        1.  golang.org/x/oauth2 v0.21.0
	2 . google.golang.org/api v0.185.0
- Updated login.html to show button for login with google. By default the google logged in Users don't have Admin access.

### CODE REVIEW

**Comment by d3vilh** [comment]
Thank you! Let me test it with different archs and we good to go with merging to main.

**Comment by droid-sheep** [comment]
@janamkhatiwada Is it possible to enhance this feature for a general implementation of OAuth? Described in #75 this feature is requested by some people (and myself). This would establish openvpn-ui to a mentionable competitor against enterprise vpn solutions with a user portal and would be interesting for companies.

I would support this but i can't write GO code.

**Comment by d3vilh** [comment]
I merge it, but updated build process, so it will support `arm64` in addition to `aarm64`.

**Comment by d3vilh** [comment]
> @janamkhatiwada Is it possible to enhance this feature for a general implementation of OAuth? Described in #75 this feature is requested by some people (and myself). This would establish openvpn-ui to a mentionable competitor against enterprise vpn solutions with a user portal and would be interesting for companies.
> 
> I would support this but i can't write GO code.

I would be glad to add it. but have new interesting project on my `main` job, which soaks all my time.

**Pull request merged**
